nasa/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nasa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('nasarover.urls')),
    url(r'^', include('userauth.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nasarover/urls.py
from django.conf.urls import patterns, url
from nasarover import views
from nasarover.views import RoverList, RoverDetail
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^newgrid/', views.newgrid, name='newgrid'),
    url(r'^senform/', views.senform, name='senform'),
    url(r'^process/', views.process, name='process'),
    url(r'^rover/$', views.RoverList.as_view()),
    url(r'^rover/(?P<pk>[0-9]+)/$', views.RoverDetail.as_view()),
)

nasarover/models.py
"""Docstring"""
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
import random


class Grid(models.Model):
    """Docstring"""
    x_len = models.IntegerField()
    y_len = models.IntegerField()


class Mineral(models.Model):
    """Docstring"""
    name = models.CharField(max_length=20)

    def __unicode__(self):
        """Docstring"""
        return self.name


class SubGrid(models.Model):
    """Docstring"""
    g_id = models.ForeignKey('Grid')
    pos_x = models.IntegerField()
    pos_y = models.IntegerField()


class MineralDis(models.Model):
    """Docstring"""
    sg_id = models.ForeignKey('SubGrid')
    mi_id = models.ForeignKey('Mineral')
    quantity = models.IntegerField()


class RoverPos(models.Model):
    """Docstring"""
    g_id = models.IntegerField()
    pos_x = models.IntegerField()
    pos_y = models.IntegerField()
    r_id = models.ForeignKey('Rover')
    dirn = models.CharField(max_length=1)

    def __unicode__(self):
        return self.r_id.name


class Rover(models.Model):
    """Docstring"""
    user_id = models.ForeignKey(User)
    rover_name = models.CharField(max_length=20)

    def __unicode__(self):
        return str(self.rover_name)

    def process_instruction(self, inst):
        """Docstring"""
        for i in range(len(inst)):
            self.move(inst[i])

    def move(self, dirn):
        """Docstring"""
        if dirn == 'R' or dirn == 'L':
            self.change_dirn(dirn)
        else:
            self.move_a_step()

    def change_dirn(self, dirn):
        """Docstring"""
        direction = "NESW"
        if dirn == 'R':
            temp_r = RoverPos.objects.get(r_id=self.id)
            temp_dirn = temp_r.dirn
            temp = direction[(direction.find(temp_dirn) + 1) % 4]
            temp_r.dirn = temp
            temp_r.save()
        else:
            temp_r = RoverPos.objects.get(r_id=self.id)
            temp_dirn = temp_r.dirn
            temp = direction[(direction.find(temp_dirn) - 1)]
            temp_r.dirn = temp
            temp_r.save()

    def increment_y(self):
        """docstring for increment_y"""
        temp = RoverPos.objects.get(r_id=self.id)
        temp.pos_y += 1
        temp.save()

    def decrement_y(self):
        """docstring for decrement_y"""
        temp = RoverPos.objects.get(r_id=self.id)
        temp.pos_y -= 1
        temp.save()

    def increment_x(self):
        """docstring for increment_x"""
        temp = RoverPos.objects.get(r_id=self.id)
        temp.pos_x += 1
        temp.save()

    def decrement_x(self):
        """docstring for decrement_x"""
        temp = RoverPos.objects.get(r_id=self.id)
        temp.pos_x -= 1
        temp.save()

    def move_a_step(self):
        """docstring for move_a_step"""
        temp = RoverPos.objects.get(r_id=self.id)
        if temp.dirn == 'N':
            self.increment_y()
        elif temp.dirn == 'E':
            self.increment_x()
        elif temp.dirn == 'S':
            self.decrement_y()
        else:
            self.decrement_x()
        self.investigate()

    def investigate(self):
        """Docstring"""
        r_sen = RoverSen.objects.filter(r_id=self.id)
        for i in r_sen:
            temp_r = i.r_id.id
            temp_m = i.m_id.id
            rovr = Rover.objects.get(id=temp_r)
            rover_pos = RoverPos.objects.get(id=temp_r)
            sg = SubGrid.objects.get(\
                g_id=rover_pos.g_id, pos_x=rover_pos.pos_x, \
                pos_y=rover_pos.pos_y)
            mnrl = Mineral.objects.get(id=temp_m)
            mn_dis = MineralDis.objects.filter(sg_id=sg, mi_id=mnrl)[0]
            if mn_dis.quantity > 0:
                mn_dis.quantity -= 1
                mn_dis.save()


class RoverSen(models.Model):
    """Docstring"""
    r_id = models.ForeignKey('Rover')
    m_id = models.ForeignKey('Mineral')

    class Meta:
        unique_together = ("r_id", "m_id")


def add_subgrid(sender, instance, **kwargs):
    """Docstring"""
    for i in range(instance.x_len):
        for j in range(instance.y_len):
            temporary = SubGrid(g_id=instance, pos_x=i, pos_y=j)
            temporary.save()


def add_mineral(sender, instance, **kwargs):
    """Docstring"""
    tot_mineral = Mineral.objects.all()
    for i in range(tot_mineral.count()):
        quan = random.randint(3, 10)
        temporary = MineralDis(
            sg_id=instance, mi_id=tot_mineral[i], quantity=quan)
        temporary.save()

post_save.connect(add_subgrid, sender=Grid)
post_save.connect(add_mineral, sender=SubGrid)

nasarover/forms.py
"""Docstring"""
from django.forms import ModelForm
from nasarover.models import Grid, SubGrid, Rover, RoverSen

class GridForm(ModelForm):
    """Docstring"""
    class Meta:
        """Docstring"""
        model = Grid
        fields = '__all__'

class RoverForm(ModelForm):
    """Docstring"""
    class Meta:
        """Docstring"""
        model = Rover
        fields = '__all__'

class RoverSenForm(ModelForm):
    """Docstring"""
    class Meta:
        """Docstring"""
        model = RoverSen
        fields = '__all__'

nasarover/views.py
"""Docstring"""
from django.shortcuts import redirect, render
from nasarover.forms import GridForm, RoverForm, RoverSenForm
from django.http import HttpResponse
from nasarover.models import Rover, RoverPos
from rest_framework import generics
from nasarover.serializers import RoverSerializer
from rest_framework import permissions

class RoverList(generics.ListCreateAPIView):
    queryset = Rover.objects.all()
    serializer_class = RoverSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    def get_queryset(self):
        if self.request.user.is_anonymous():
            return Rover.objects.all()
        else:
            return Rover.objects.filter(user_id = self.request.user)


class RoverDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Rover.objects.all()
    serializer_class = RoverSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

def index(request):
    """Docstring"""
    if not request.user.is_authenticated():
        return redirect('accounts/login/')
    sform = RoverSenForm()
    form = RoverForm()
    c = {'form': form, 'sform': sform}
    return render(request, 'index.html', c)


def newgrid(request):
    """Docstring"""
    if not request.user.is_authenticated():
        return redirect('accounts/login/')
    if request.method == 'POST':
        form = GridForm(request.POST)
        if True:
            my_model = form.save()
    else:
        form = GridForm()
    c = {'form': form}
    return render(request, 'grid.html', c)


def senform(request):
    """Docstring"""
    if request.method == 'POST':
        form = RoverSenForm(request.POST)
        if True:
            my_model = form.save()
        return redirect('/')
    else:
        return HttpResponseNotFound('<h1>Page not found</h1>')


def process(request):
    """Docstring"""
    if request.method == 'POST':
        r_id = request.POST['rovr']
        r_inst = request.POST['inst']
        grid = request.POST['grid']
        grid_x = request.POST['grid_x']
        grid_y = request.POST['grid_y']
        dirn = request.POST['dirn']
        upd = request.POST.get('upd', False)
        temp_r = Rover.objects.get(id=r_id)
        rovr = RoverPos.objects.filter(id=r_id)
        if len(rovr) < 1:
            rovr = RoverPos(
                g_id=grid, pos_x=grid_x, pos_y=grid_y, r_id=temp_r, dirn=dirn)
            rovr.save()
        if upd:
            rovr_pos = RoverPos.objects.get(id=r_id)
            rovr_pos.g_id = grid
            rovr_pos.pos_x = grid_x
            rovr_pos.pos_y = grid_y
            rovr_pos.r_id = temp_r
            rovr_pos.dirn = dirn
            rovr_pos.save()
        temp_r.process_instruction(r_inst)
        rover_pos = RoverPos.objects.get(id=r_id)
        s = "Final position of rover :  X = " + str(rover_pos.pos_x) + \
            "  Y = " + str(rover_pos.pos_y)\
            + "  Dirn = " + str(rover_pos.dirn)
        return HttpResponse(s)
    else:
        return HttpResponseNotFound('<h1>Page not found</h1>')

nasarover/templates/grid.html
{% extends "base.html" %}

{%block content%}
<form action="/newgrid/" method="POST">
    {%csrf_token%}
    <table class="table">
    {{form}}
    </table>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
{%endblock content%}

nasarover/templates/index.html
{% extends "base.html" %}

{% block content %}
<a href='/newgrid/'> Create new Grid ({{user.get_username}})</a>
{%if user.is_authenticated %}
    <a class="btn btn-default" href="accounts/logout/"> Logout </a>
{%endif%}
</br>
<div ng-controller="NasaCtrl">
    <button ng-click="allrover()" class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Get all Rovers
    </button>
    <div class="collapse" id="collapseExample">
      <div class="well" ng-bind-html="whatever">
      </div>
    </div>
</div>
<h3> Create a robot </h3>
<div>
<form ng-controller="NasaCtrl" ng-submit="roversave()" name = roverForm>
    {%csrf_token%}
    <label for="id_user_id">User id:</label>
    <input id="id_rover_name" ng-model="data.user_id" type="text" />
    <h6>{[{data.user_id}]}</h6>
    <label for="id_rover_name">Rover name:</label>
    <input id="id_rover_name" ng-model="data.rover_name" type="text" />
    <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>

<h3> Add some mineral </h3>
<form action="/senform/" method="POST">
    {%csrf_token%}
    <table class="table">
    {{sform}}
    </table>
    <button type="submit" class="btn btn-default">Submit</button>
</form>


<h3> Give instructions to process </h3>
<form action="process/" method = "POST">
    {%csrf_token%}
    <tr>
        <th>
            <label for="id_rovr">Rover id:</label>
        </th>
        <td>
            <input id="id_rovr" maxlength="100" name="rovr" type="text" />
        </td>
        </br>
        <input type="checkbox" name="upd" value="Update" default=on> Update pos?<br>
        <th>
            <label for="id_rovr">Grid id:</label>
        </th>
        <td>
            <input id="id_rovr" maxlength="100" name="grid" type="text" />
        </td>
        <th>
            <label for="id_rovr">Grid Pos x:</label>
        </th>
        <td>
            <input id="id_rovr" maxlength="100" name="grid_x" type="text" />
        </td>
        <th>
            <label for="id_rovr">Grid pos Y:</label>
        </th>
        <td>
            <input id="id_rovr" maxlength="100" name="grid_y" type="text" />
        </td>
        </br>
        </br>
        <th>
            <label for="id_rovr">Rover dirn:</label>
        </th>
        <td>
            <input id="id_rovr" maxlength="1" name="dirn" type="text" />
        </td>
        <th>
            <label for="id_inst">Instructions :</label>
        </th>
        <td>
            <input id="id_inst" maxlength="100" name="inst" type="text" />
        </td>
    </tr>
    <button type="submit" class="btn btn-default">Process</button>
</form>

{% endblock %}